# Usando la version 3.8 del esquema de Docker Compose
# Esto no es la version de Docker, sino del formato de docker-compose.yml
version: '3.8'

services:
  mlflow-model:
    # Servicio que expone el modelo MLflow
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlflow-model
    ports:
      - "1234:1234"
    networks:
      - mlflow-net

  mlflow-ui:
    # Servicio que levanta la interfaz web de MLflow
    image:  python:3.9-slim
    container_name: mlflow-ui
    working_dir: /app
    volumes:
      - .:/app # Monta proyecto local al contenedor
    ports:
      - "5000:5000"
    networks:
      - mlflow-net
    command: >
      sh -c "pip install mlflow && mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri file:/app/mlruns"

  mlflow-tester-single:
    # Servicio que ejecuta el script test_mlflow.py (single predictions)
    build:
      context: .
      dockerfile: Dockerfile-tester-single
    container_name: mlflow-tester-single
    depends_on:
      - mlflow-model # Asegura que el modelo se levante primero
    environment:
      - MLFLOW_HOST=mlflow-model
    networks:
      - mlflow-net
    
  mlflow-tester-batch:
    # Servicio que ejecuta el script test_mlflow_batch.py (batch predictions)
    build:
      context: .
      dockerfile: Dockerfile-tester-batch
    container_name: mlflow-tester-batch
    depends_on:
      - mlflow-model
    environment:
      - MLFLOW_HOST=mlflow-model
    networks:
      - mlflow-net

# Red interna que permite que los servicios se comuniquen por nombre
networks:
  mlflow-net:
    driver: bridge