# Usa una imagen base oficial de Python
FROM python:3.9-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo de dependencias al contenedor
COPY requirements.txt .

# Instala las dependencias necesarias
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo el contenido del proyecto al contenedor
COPY . .

# Comando por defecto:
# Espera 10 segundos para dar tiempo a que el modelo se levante
# Luego ejecuta el script test_mlflow.py
CMD sleep 10 && python scripts/test_mlflow.py
